version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.3.0
    container_name: artifactory-oss
    ports:
     - 8081:8081
    volumes:
     - artifactory-oss:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
volumes:
  artifactory-oss:
